insert into car_table (car_model, car_release_year, car_company, car_color) values ('DB9', 2008, 'Aston Martin', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Probe', 1992, 'Ford', 'Orange');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Jetta III', 1993, 'Volkswagen', 'Indigo');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Avalanche 1500', 2003, 'Chevrolet', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Econoline E350', 1995, 'Ford', 'Teal');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Corvette', 2011, 'Chevrolet', 'Goldenrod');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('300SD', 1992, 'Mercedes-Benz', 'Green');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('E-Series', 2010, 'Ford', 'Purple');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Rendezvous', 2004, 'Buick', 'Fuscia');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Envoy', 1998, 'GMC', 'Fuscia');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Quest', 1996, 'Nissan', 'Mauv');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Murano', 2006, 'Nissan', 'Violet');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Yaris', 2006, 'Toyota', 'Fuscia');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Sephia', 1998, 'Kia', 'Indigo');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Passat', 2004, 'Volkswagen', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('CL-Class', 2000, 'Mercedes-Benz', 'Fuscia');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('C-Class', 1995, 'Mercedes-Benz', 'Aquamarine');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Vandura G3500', 1995, 'GMC', 'Violet');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('SRX', 2006, 'Cadillac', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Continental', 2006, 'Bentley', 'Red');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Explorer Sport Trac', 2003, 'Ford', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Taurus', 1993, 'Ford', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Accent', 2002, 'Hyundai', 'Crimson');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Taurus', 2003, 'Ford', 'Purple');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Neon', 2000, 'Dodge', 'Orange');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Mirage', 1993, 'Mitsubishi', 'Crimson');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Venza', 2013, 'Toyota', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('RX', 2000, 'Lexus', 'Orange');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Passat', 1998, 'Volkswagen', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Mustang', 1968, 'Ford', 'Indigo');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Rio', 2006, 'Kia', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Murciélago', 2009, 'Lamborghini', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Impala', 2003, 'Chevrolet', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Escalade ESV', 2011, 'Cadillac', 'Goldenrod');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Probe', 1990, 'Ford', 'Crimson');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Tercel', 1998, 'Toyota', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Yukon XL 2500', 2001, 'GMC', 'Crimson');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('W201', 1991, 'Mercedes-Benz', 'Purple');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Civic', 1993, 'Honda', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('RSX', 2003, 'Acura', 'Pink');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('RS 4', 2007, 'Audi', 'Red');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('RX-7', 1989, 'Mazda', 'Blue');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Frontier', 2003, 'Nissan', 'Fuscia');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Grand Am', 1985, 'Pontiac', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Galant', 2011, 'Mitsubishi', 'Teal');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Xterra', 2007, 'Nissan', 'Pink');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('F250', 1984, 'Ford', 'Blue');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Ram 1500', 2006, 'Dodge', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Mirage', 2000, 'Mitsubishi', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Camry', 1994, 'Toyota', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('SRX', 2004, 'Cadillac', 'Indigo');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Grand Marquis', 1994, 'Mercury', 'Teal');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Grand Voyager', 1998, 'Plymouth', 'Orange');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Explorer Sport', 2003, 'Ford', 'Blue');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Econoline E250', 1997, 'Ford', 'Goldenrod');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('LX', 2000, 'Lexus', 'Orange');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Ridgeline', 2012, 'Honda', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Econoline E150', 1996, 'Ford', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('i-290', 2007, 'Isuzu', 'Goldenrod');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('TL', 1996, 'Acura', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Thunderbird', 1992, 'Ford', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('929', 1995, 'Mazda', 'Violet');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Hombre Space', 1998, 'Isuzu', 'Pink');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Escort', 1994, 'Ford', 'Goldenrod');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Frontier', 2003, 'Nissan', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('7 Series', 1996, 'BMW', 'Teal');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Passport', 1995, 'Honda', 'Fuscia');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('GLI', 2008, 'Volkswagen', 'Pink');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Tundra', 2008, 'Toyota', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('STS', 2007, 'Cadillac', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Silverado 3500', 2002, 'Chevrolet', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('MX-3', 1993, 'Mazda', 'Indigo');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Freelander', 2004, 'Land Rover', 'Pink');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('TrailBlazer', 2007, 'Chevrolet', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Mazda6', 2003, 'Mazda', 'Mauv');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('4Runner', 2007, 'Toyota', 'Orange');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Catera', 1999, 'Cadillac', 'Goldenrod');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Golf', 2003, 'Volkswagen', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Mazda6', 2012, 'Mazda', 'Red');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Continental', 1999, 'Lincoln', 'Pink');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('G-Series 3500', 1998, 'Chevrolet', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('XK Series', 2001, 'Jaguar', 'Teal');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Continental Mark VII', 1990, 'Lincoln', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Summit', 1994, 'Eagle', 'Indigo');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Sienna', 2007, 'Toyota', 'Maroon');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Lumina', 1999, 'Chevrolet', 'Indigo');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Silverado 1500', 2011, 'Chevrolet', 'Goldenrod');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('B-Series Plus', 1992, 'Mazda', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Fusion', 2013, 'Ford', 'Mauv');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Discovery', 2005, 'Land Rover', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Prius', 2006, 'Toyota', 'Crimson');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Mustang', 1974, 'Ford', 'Blue');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Corvette', 2010, 'Chevrolet', 'Blue');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Silverado', 2001, 'Chevrolet', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Mustang', 1990, 'Ford', 'Yellow');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Astro', 2004, 'Chevrolet', 'Turquoise');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Sprinter', 2009, 'Dodge', 'Red');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Impreza', 1996, 'Subaru', 'Teal');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('Marauder', 2003, 'Mercury', 'Khaki');
insert into car_table (car_model, car_release_year, car_company, car_color) values ('SLK-Class', 2008, 'Mercedes-Benz', 'Crimson');
